name: PROXY Updater

on:
  workflow_dispatch: # Enable manual trigger
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests geoip2
    - name: Download GeoLite2 Database
      run: |
        curl -s -L https://git.io/GeoLite2-Country.mmdb
    - name: Execute script
      run: |
        python main.py
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.GH_EMAIL }}
        git config --local user.name ${{ secrets.GH_NAME }}
        git add -A
        git commit -m "Updated Proxies" || exit 0 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
