name: PROXY Updater

on:
  workflow_dispatch: # Enable manual trigger
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install requests geoip2
    - name: Download GeoLite2 Database
      run:
        curl -s -L https://git.io/GeoLite2-Country.mmdb -o GeoLite2-Country.mmdb
    - name: Download Proxy Check
      run:
        curl -s -L https://github.com/mmpx12/proxy-check/releases/download/v1.1.1/proxy-check-v1.1.1-linux-amd64.tar.gz -o proxy-check.tar.gz &&
        tar xvf proxy-check.tar.gz -C proxy-check
        
    - name: Execute script
      run: python main.py

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update proxies_{country}.txt
